name: DevOps Examen

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "npm"
      - run: npm ci

  check_code_quality:
    runs-on: ubuntu-latest
    needs: [check_install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run prettier

  check_test:
    runs-on: ubuntu-latest
    needs: [check_install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "npm"
      - run: npm ci
      - run: npm test

  check_build:
    runs-on: ubuntu-latest
    needs: [check_code_quality, check_test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "npm"
      - run: npm ci
      - run: npm run build